name: ci - docker-test

on:
  workflow_dispatch:

jobs:
  docker-test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Register QEMU emulators
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Run cross-arch container test
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/userdocs/qbt-musl-cross-make:riscv64-linux-musl
          options: --privileged
          run: |
            set -eux
            echo "--- Checking compiler ---"
            file /usr/local/bin/riscv64-linux-musl-gcc
            /usr/local/bin/gcc -v

            echo "--- Creating source file ---"
            cat > hello.c << 'EOF'
            #include <stdio.h>
            int main() {
                printf("Hello World!\n");
                return 0;
            }
            EOF

            echo "--- Compiling binary ---"
            gcc -static -o hello hello.c

            echo "--- Checking binary type ---"
            file ./hello

            echo "--- Running binary ---"
            ./hello

  docker-test-2:
    runs-on: ubuntu-latest
    steps:
      - name: Register QEMU emulators
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Run cross-arch container test
        run: |
          echo "--- Creating source file ---"
          cat > hello.c << 'EOF'
          #include <stdio.h>
          int main() {
              printf("Hello World!\n");
              return 0;
          }
          EOF

      - name: Run cross-arch container test
        run: >
          docker run -v ~/:/root -w /root ghcr.io/userdocs/qbt-musl-cross-make:riscv64-linux-musl bash -c '
          echo "--- Checking compiler ---" &&
          file /usr/local/bin/riscv64-linux-musl-gcc &&
          /usr/local/bin/gcc -v &&

          echo "--- Compiling binary ---" &&
          gcc -static -o hello hello.c &&

          echo "--- Checking binary type ---" &&
          file ./hello &&

          echo "--- Running binary ---" &&
          ./hello'
