name: ci - docker-test

on:
  workflow_dispatch:

jobs:
  docker-test-2:
    runs-on: ubuntu-latest
    steps:
      - name: Register QEMU emulators
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: create test file
        run: |
          echo "--- Creating source file ---"
          cat > hello.c << 'EOF'
          #include <stdio.h>
          int main() {
              printf("Hello World!\n");
              return 0;
          }
          EOF

      - name: bootstrap
        run: >
          docker run -v ${{ github.workspace }}:/root -w /root ghcr.io/userdocs/qbt-musl-cross-make:riscv64-linux-musl bash -c '
          echo "--- Checking compiler ---" &&
          file /usr/local/bin/riscv64-linux-musl-gcc &&
          /usr/local/bin/gcc -v'

      - name: Run cross-arch container gcc info
        run: >
          docker run -v ${{ github.workspace }}:/root -w /root ghcr.io/userdocs/qbt-musl-cross-make:riscv64-linux-musl bash -c '
          echo "--- Checking compiler ---" &&
          file /usr/local/bin/riscv64-linux-musl-gcc &&
          /usr/local/bin/gcc -v'

      - name: Run cross-arch container gcc build
        run: >
          docker run -v ${{ github.workspace }}:/root -w /root ghcr.io/userdocs/qbt-musl-cross-make:riscv64-linux-musl bash -c '
          echo "--- Compiling binary ---" &&
          gcc -static -o hello hello.c'

      - name: Run cross-arch container qemu run
        run: >
          docker run -v ${{ github.workspace }}:/root -w /root ghcr.io/userdocs/qbt-musl-cross-make:riscv64-linux-musl bash -c '
          echo "--- Checking binary type ---" &&
          file ./hello &&

          echo "--- Running binary ---" &&
          ./hello'
