name: "02 docker"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container_image }}
    strategy:
      fail-fast: false
      matrix:
        runs_on: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        container_image: [
          "ubuntu:latest",
          "debian:latest",
          "alpine:latest",
          "fedora:latest",
          "rockylinux:latest",
          "almalinux:latest",
          "opensuse/leap:latest"
        ]
    steps:


      - run: apk add bash
        if: matrix.container_image == 'alpine:latest'

      - run: arch | tee -a $GITHUB_STEP_SUMMARY

      - run: |
          curl -sLO "https://raw.githubusercontent.com/userdocs/test/refs/heads/main/qi.bash"
          chmod +x qi.bash
          ./qi.bash

