name: "14"

on:
  workflow_dispatch:

jobs:
  boost_version:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: run id
        run: |
          gh --version
          gh workflow run test-14-runme.yml
