name: "02 docker"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ["amd64", "arm/v6", "arm/v7", "arm64", "i386", "riscv64", "mips64le", "ppc64le", "s390x"]
        container_image: [
          "ubuntu:latest",
          "debian:latest",
          "alpine:latest",
          "rockylinux:latest"
          # "almalinux:latest",
          # "opensuse/leap:latest",
          # "fedora:latest",
        ]
        exclude:
          - platform: "mips64le"
            container_image: "alpine:latest"

    env:
        container_name: "build"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - run: ls /lib/*

      - name: Create docker ${{ env.container_name }} ${{ matrix.container_image }} ${{ matrix.platform }} container
        run: >
          docker run --name ${container_name} -it -d -w /root -v ${{ github.workspace }}:/root
          --platform linux/${{ matrix.platform }}
          ${{ matrix.container_image }}


      - name: Run apk update
        if: matrix.container_image == 'alpine:latest'
        run: docker exec ${container_name} apk add bash

      - name: Run apk update
        if: matrix.container_image == 'ubuntu:latest'
        run: docker exec ${container_name} apt-get update && apt-get install -y wget

      - name: Run apk update
        if: matrix.container_image == 'debian:latest'
        run: docker exec ${container_name} apt-get update && apt-get install -y wget

      - name: Run apk update
        if: matrix.container_image == 'rockylinux:latest'
        run: docker exec ${container_name} yum install -y wget

      - run: docker exec ${container_name} sh -c "arch"

      - run: |
          chmod +x qi.bash
          docker exec ${container_name} bash qi.bash

