name: ci - docker-test

on:
  workflow_dispatch:

jobs:
  qemu-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Register QEMU emulators
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

  docker-test:
    needs: qemu-setup
    runs-on: ubuntu-latest # use a standard runner so QEMU works
    container:
      image: ghcr.io/userdocs/qbt-musl-cross-make:riscv64-linux-musl
      options: --privileged # allow binfmt_misc to be visible

    steps:
      - name: file gcc
        run: file /usr/local/bin/riscv64-linux-musl-gcc

      - name: gcc -v
        run: /usr/local/bin/gcc -v

      - name: Create Hello World source
        run: |
          cat > hello.c << 'EOF'
          #include <stdio.h>
          int main() {
              printf("Hello World!\n");
              return 0;
          }
          EOF

      - name: Compile static Hello World binary
        run: gcc -static -o hello hello.c

      - name: file hello
        run: file ./hello

      - name: Test Hello World binary
        run: ./hello
