name: ca test 12

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  eventcontext:
    runs-on: ubuntu-24.04
    steps:
      - name: Dump GitHub event context
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_type: ${{ github.ref_type }}"
          echo "github.sha: ${{ github.sha }}"
          echo "github.triggering_actor: ${{ github.triggering_actor }}"
          sleep 30
