name: ci - docker-test

on:
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-24.04-arm
    container: ghcr.io/userdocs/qbt-musl-cross-make:riscv64-linux-musl

    steps:
      - name: file gcc
        env:
          arch_type: ${{ matrix.arch_type }}
        run: file /usr/local/bin/${arch_type}-gcc

      - name: gcc -v
        env:
          arch_type: ${{ matrix.arch_type }}
        run: /usr/local/bin/gcc -v

      - name: Create Hello World source
        run: |
          cat > hello.c << 'EOF'
          #include <stdio.h>
          int main() {
              printf("Hello World!\n");
              return 0;
          }
          EOF

      - name: Compile static Hello World binary
        env:
          arch_type: ${{ matrix.arch_type }}
        run: |
          gcc -static -o hello hello.c

      - name: file hello
        run: file ./hello

      - name: Test Hello World binary
        run: |
          apk add update
          apk add qemu qemu-openrc
          ./hello
