name: "02 docker"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        platform: ["amd64", "arm/v6", "arm/v7", "arm64", "i386", "mips64le", "ppc64le", "riscv64", "s390x"]
        container_image: [
          # "ubuntu:latest",
          # "debian:latest",
          "alpine:latest"
          # "rockylinux:latest",
          # "almalinux:latest",
          # "opensuse/leap:latest",
          # "fedora:latest",
        ]
    env:
        container_name: "build"
    steps:
      - name: Create docker ${{ env.container_name }} ${{ matrix.container_image }} ${{ matrix.platform }} container
        run: >
          docker run --name ${container_name} -it -d -w /root -v ${{ github.workspace }}:/root
          --platform linux/${{ matrix.platform }}
          ${{ matrix.container_image }}


      - name: Run apk update
        if: matrix.container_image == 'alpine:latest'
        run: docker exec ${container_name} apk add bash

      - run: docker exec ${container_name} arch

      - run: |
          curl -sLO "https://raw.githubusercontent.com/userdocs/test/refs/heads/main/qi.bash"
          chmod +x qi.bash
          docker exec ${container_name} bash qi.bash

