name: "14"

on:
  workflow_dispatch:

jobs:
  boost_version:
    runs-on: ubuntu-24.04-arm
    permissions:
      actions: write
      contents: write

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Host - checkout
        uses: actions/checkout@v6 # v5.0.0
        with:
          persist-credentials: false

      - name: run id
        run: |
          curl -sLo- https://github.com/cli/cli/releases/download/v2.87.2/gh_2.87.2_linux_arm64.tar.gz | tar xzf - --strip-components=1 -C ~/
          chmod +x ~/bin/gh
          ~/bin/gh workflow run test-14-runme.yml
