name: "02 docker"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container:
      image: ${{ matrix.container_image }}
      options: --platform linux/${{ matrix.platform }}
      # volumes:
      #   - ${{ github.workspace }}:/root
    strategy:
      fail-fast: false
      matrix:
        platform: ["amd64", "arm/v6", "arm/v7", "arm64", "i386", "mips64le", "ppc64le", "riscv64", "s390x"]
        container_image: [
          "ubuntu:latest",
          "debian:latest",
          "alpine:latest"
          # "rockylinux:latest",
          # "almalinux:latest",
          # "opensuse/leap:latest",
          # "fedora:latest",
        ]
    steps:


      - run: apk add bash
        if: matrix.container_image == 'alpine:latest'

      - run: arch | tee -a $GITHUB_STEP_SUMMARY

      - run: |
          curl -sLO "https://raw.githubusercontent.com/userdocs/test/refs/heads/main/qi.bash"
          chmod +x qi.bash
          ./qi.bash

