name: "12"

on:
  workflow_dispatch:

jobs:
  boost_version:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        libtorrent:
          - version: "[2.0.11, 1.2.20]"
            boost_major_version: "1"
            boost_minor_version: "77"
            boost_patch_version: "0"
        qbt_gui: ["GUI=ON", "GUI=OFF"]
        qt_version: ["6.10.1"]

    name: "libt-${{ matrix.libtorrent.version }} | boost-1.${{ matrix.libtorrent.boost_minor_version }} | ${{ matrix.qbt_gui }}"

    steps:
      - name: Show outcome
        run: |
          echo "## Build Configuration" >> $GITHUB_STEP_SUMMARY
          echo "| Parameter | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| libtorrent | ${{ matrix.libtorrent.version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| boost_major_version | ${{ matrix.libtorrent.boost_major_version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| boost_minor_version | ${{ matrix.libtorrent.boost_minor_version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| boost_patch_version | ${{ matrix.libtorrent.boost_patch_version }} |" >> $GITHUB_STEP_SUMMARY
          echo "| qbt_gui | ${{ matrix.qbt_gui }} |" >> $GITHUB_STEP_SUMMARY
          echo "| qt_version | ${{ matrix.qt_version }} |" >> $GITHUB_STEP_SUMMARY
