name: "15"

on:
  workflow_dispatch:

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-test-2:
    runs-on: ubuntu-latest
    steps:
      - name: create test file
        run: |
          echo sleep 180
          sleep 180

      - name: test
        if: cancelled()
        env:
          GH_TOKEN: ${{ secrets.TEST }}
        run: |
          # List notifications, filter for "workflow run cancelled", and mark them as done
          gh api notifications --jq '.[] | select(.subject.title | contains("workflow run cancelled")) | .id' | while read id; do
              echo "$id"
              gh api -X DELETE "notifications/threads/$id"
          done
