name: "10"

on:
  workflow_dispatch:

jobs:
  build-1:
    runs-on: macos-13

    steps:
      - name: openssl@3
        run: |
          brew install openssl@3

      - name: openssl@1.1
        run: |
          brew install openssl@1.1

  build-2:
    runs-on: macos-14

    steps:
      - name: openssl@3
        run: |
          brew install openssl@3

      - name: openssl@1.1
        run: |
          brew install openssl@1.1

  build-3:
    runs-on: macos-15

    steps:
      - name: openssl@3
        run: |
          brew install openssl@3

      - name: openssl@1.1
        run: |
          brew install openssl@1.1

